[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions."*"]
  included_files = ["dist/**"]

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"


[functions."*"]
  included_files = ["dist/**"]

[functions.api]
  timeout = 30